version: '3'

vars:
  PROJECT_NAME: openrouter-tracker
  PYTHON_PATH: ./venv/bin/python3
  PIP_PATH: ./venv/bin/pip

tasks:
  setup:
    desc: Setup the project with virtual environment and dependencies
    cmds:
      - 'echo "Setting up {{.PROJECT_NAME}}..."'
      - 'mkdir -p logs'
      - 'python3 -m venv venv'
      - 'echo "venv/" > .gitignore'
      - 'echo "__pycache__/" >> .gitignore'
      - 'echo "*.db" >> .gitignore'
      - 'echo "config.yaml" >> .gitignore'
      - 'echo "logs/" >> .gitignore'
      - '{{.PIP_PATH}} install --upgrade pip'
      - '{{.PIP_PATH}} install -r requirements.txt'
      - 'chmod +x fetch_openrouter.py'
      - '{{.PYTHON_PATH}} -c "from db import Database; db = Database(''models.db''); db.__enter__(); db.init_db()"'
      - 'echo "Setup complete!"'
      - 'echo "Next steps:"'
      - 'echo "1. Edit config.yaml with your Discord webhook URL"'
      - 'echo "2. Run: task run"'
      - 'echo "3. Add to crontab: crontab -e"'

  run:
    desc: Run the main script to fetch OpenRouter data (requires dotenvx)
    deps: [setup]
    cmds:
      - |
        if ! command -v dotenvx &> /dev/null; then
          echo "Error: dotenvx is required but not found."
          echo "Please install dotenvx from https://dotenvx.com/"
          exit 1
        fi
        dotenvx exec -- {{.PYTHON_PATH}} fetch_openrouter.py

  test:
    desc: Run all tests
    deps: [setup]
    cmds:
      - 'echo "Running unit tests..."'
      - '{{.PYTHON_PATH}} -m pytest tests/ -v'
      - '{{.PYTHON_PATH}} tests/test_script.py'
      - '{{.PYTHON_PATH}} test_table_format.py'
      - '{{.PYTHON_PATH}} test_discord_notification.py'

  test-unit:
    desc: Run unit tests only
    deps: [setup]
    cmds:
      - '{{.PYTHON_PATH}} -m pytest tests/ -v'

  test-format:
    desc: Run table format test
    deps: [setup]
    cmds:
      - '{{.PYTHON_PATH}} test_table_format.py'

  test-discord:
    desc: Run Discord notification test
    deps: [setup]
    cmds:
      - '{{.PYTHON_PATH}} test_discord_notification.py'

  lint:
    desc: Run linters (ruff check and format)
    cmds:
      - 'ruff check .'
      - 'ruff format .'

  lint-fix:
    desc: Run linters and fix issues
    cmds:
      - 'ruff check . --fix'
      - 'ruff format .'

  clean:
    desc: Clean up temporary files and virtual environment
    cmds:
      - 'rm -rf venv/'
      - 'rm -rf __pycache__/'
      - 'rm -rf */__pycache__/'
      - 'rm -rf .ruff_cache/'
      - 'find . -type f -name "*.pyc" -delete'
      - 'find . -type d -name "__pycache__" -delete'

  clean-logs:
    desc: Clean up log files
    cmds:
      - 'rm -f logs/*.log'
      - 'find logs/ -name "*.log.*" -delete || true'

  clean-db:
    desc: Clean up database files
    cmds:
      - 'rm -f *.db'
      - 'rm -f *.db-shm'
      - 'rm -f *.db-wal'

  reset:
    desc: Clean up and reset the project
    cmds:
      - 'task: clean'
      - 'task: clean-logs'
      - 'task: clean-db'

  install-deps:
    desc: Install dependencies only
    cmds:
      - 'python3 -m venv venv'
      - '{{.PIP_PATH}} install --upgrade pip'
      - '{{.PIP_PATH}} install -r requirements.txt'

  update-deps:
    desc: Update dependencies
    cmds:
      - '{{.PIP_PATH}} install --upgrade -r requirements.txt'

  check-config:
    desc: Check if config.yaml exists
    cmds:
      - |
        if [ ! -f config.yaml ]; then
          echo "config.yaml not found. Please create it from config.yaml.example or manually."
          exit 1
        else
          echo "config.yaml exists."
        fi

  init-db:
    desc: Initialize the database
    deps: [setup]
    cmds:
      - '{{.PYTHON_PATH}} -c "from db import Database; db = Database(''models.db''); db.__enter__(); db.init_db()"'

  cron-setup:
    desc: Setup cron job for automatic execution
    cmds:
      - |
        echo "Setting up cron job for twice daily execution..."
        echo "Add the following to your crontab (run 'crontab -e'):"
        echo "0 6 * * * cd $(pwd) && $(pwd)/venv/bin/python3 fetch_openrouter.py"
        echo "0 18 * * * cd $(pwd) && $(pwd)/venv/bin/python3 fetch_openrouter.py"

  status:
    desc: Show project status
    cmds:
      - 'echo "Project: {{.PROJECT_NAME}}"'
      - 'echo "Python: $(python3 --version)"'
      - 'echo "Virtual environment: $(test -d venv && echo ''exists'' || echo ''missing'')"'
      - 'echo "Dependencies: $(test -f requirements.txt && echo ''available'' || echo ''missing'')"'
      - 'echo "Config: $(test -f config.yaml && echo ''exists'' || echo ''missing'')"'
      - 'echo "Database: $(test -f models.db && echo ''exists'' || echo ''missing'')"'
      - 'echo "Logs directory: $(test -d logs && echo ''exists'' || echo ''missing'')"'

  help:
    desc: Show available tasks
    cmds:
      - 'task --list'